# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/alexj/Downloads/Soc_FinalProject-Task2/project_2.xpr/project_2/project_2.ipdefs/ip_repo/src/design_6_ooc.xdc

# IP: C:/Users/alexj/Downloads/Soc_FinalProject-Task2/project_2.xpr/project_2/project_2.ipdefs/ip_repo/src/design_6_hdmi_tx_0_0/design_6_hdmi_tx_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_6_hdmi_tx_0_0 || ORIG_REF_NAME==design_6_hdmi_tx_0_0} -quiet] -quiet

# IP: C:/Users/alexj/Downloads/Soc_FinalProject-Task2/project_2.xpr/project_2/project_2.ipdefs/ip_repo/src/design_6_clk_wiz_0_0/design_6_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_6_clk_wiz_0_0 || ORIG_REF_NAME==design_6_clk_wiz_0_0} -quiet] -quiet

# IP: C:/Users/alexj/Downloads/Soc_FinalProject-Task2/project_2.xpr/project_2/project_2.ipdefs/ip_repo/src/design_6_util_vector_logic_0_0/design_6_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_6_util_vector_logic_0_0 || ORIG_REF_NAME==design_6_util_vector_logic_0_0} -quiet] -quiet

# XDC: c:/users/alexj/downloads/soc_finalproject-task2/project_2.xpr/project_2/project_2.tmp/myip_pong2_v1_0_project/myip_pong2_v1_0_project.gen/sources_1/ip/design_6_clk_wiz_0_0/design_6_clk_wiz_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_6_clk_wiz_0_0 || ORIG_REF_NAME==design_6_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/users/alexj/downloads/soc_finalproject-task2/project_2.xpr/project_2/project_2.tmp/myip_pong2_v1_0_project/myip_pong2_v1_0_project.gen/sources_1/ip/design_6_clk_wiz_0_0/design_6_clk_wiz_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_6_clk_wiz_0_0 || ORIG_REF_NAME==design_6_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/users/alexj/downloads/soc_finalproject-task2/project_2.xpr/project_2/project_2.tmp/myip_pong2_v1_0_project/myip_pong2_v1_0_project.gen/sources_1/ip/design_6_clk_wiz_0_0/design_6_clk_wiz_0_0_late.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_6_clk_wiz_0_0 || ORIG_REF_NAME==design_6_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/users/alexj/downloads/soc_finalproject-task2/project_2.xpr/project_2/project_2.tmp/myip_pong2_v1_0_project/myip_pong2_v1_0_project.gen/sources_1/ip/design_6_clk_wiz_0_0/design_6_clk_wiz_0_0_ooc.xdc
