# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/alexj/Downloads/Soc_FinalProject-Task2/project_2.xpr/project_2/project_2.srcs/sources_1/bd/design_1/ip/design_1_myip_pong2_0_0/design_1_myip_pong2_0_0.xci
# IP: The module: 'design_1_myip_pong2_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/alexj/Downloads/Soc_FinalProject-Task2/project_2.xpr/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_myip_pong2_0_0/src/design_6_util_vector_logic_0_0/design_6_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_6_util_vector_logic_0_0 || ORIG_REF_NAME==design_6_util_vector_logic_0_0} -quiet] -quiet

# IP: c:/Users/alexj/Downloads/Soc_FinalProject-Task2/project_2.xpr/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_myip_pong2_0_0/src/design_6_clk_wiz_0_0/design_6_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_6_clk_wiz_0_0 || ORIG_REF_NAME==design_6_clk_wiz_0_0} -quiet] -quiet

# IP: c:/Users/alexj/Downloads/Soc_FinalProject-Task2/project_2.xpr/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_myip_pong2_0_0/src/design_6_hdmi_tx_0_0/design_6_hdmi_tx_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_6_hdmi_tx_0_0 || ORIG_REF_NAME==design_6_hdmi_tx_0_0} -quiet] -quiet

# XDC: c:/Users/alexj/Downloads/Soc_FinalProject-Task2/project_2.xpr/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_myip_pong2_0_0/src/design_6_clk_wiz_0_0/design_6_clk_wiz_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_6_clk_wiz_0_0 || ORIG_REF_NAME==design_6_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/alexj/Downloads/Soc_FinalProject-Task2/project_2.xpr/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_myip_pong2_0_0/src/design_6_clk_wiz_0_0/design_6_clk_wiz_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_6_clk_wiz_0_0 || ORIG_REF_NAME==design_6_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/alexj/Downloads/Soc_FinalProject-Task2/project_2.xpr/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_myip_pong2_0_0/src/design_6_clk_wiz_0_0/design_6_clk_wiz_0_0_late.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_6_clk_wiz_0_0 || ORIG_REF_NAME==design_6_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/alexj/Downloads/Soc_FinalProject-Task2/project_2.xpr/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_myip_pong2_0_0/src/design_6_clk_wiz_0_0/design_6_clk_wiz_0_0_ooc.xdc

# XDC: c:/Users/alexj/Downloads/Soc_FinalProject-Task2/project_2.xpr/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_myip_pong2_0_0/src/design_6_ooc.xdc

# IP: C:/Users/alexj/Downloads/Soc_FinalProject-Task2/project_2.xpr/project_2/project_2.srcs/sources_1/bd/design_1/ip/design_1_myip_pong2_0_0/design_1_myip_pong2_0_0.xci
# IP: The module: 'design_1_myip_pong2_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/alexj/Downloads/Soc_FinalProject-Task2/project_2.xpr/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_myip_pong2_0_0/src/design_6_util_vector_logic_0_0/design_6_util_vector_logic_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_6_util_vector_logic_0_0 || ORIG_REF_NAME==design_6_util_vector_logic_0_0} -quiet] -quiet

# IP: c:/Users/alexj/Downloads/Soc_FinalProject-Task2/project_2.xpr/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_myip_pong2_0_0/src/design_6_clk_wiz_0_0/design_6_clk_wiz_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_6_clk_wiz_0_0 || ORIG_REF_NAME==design_6_clk_wiz_0_0} -quiet] -quiet

# IP: c:/Users/alexj/Downloads/Soc_FinalProject-Task2/project_2.xpr/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_myip_pong2_0_0/src/design_6_hdmi_tx_0_0/design_6_hdmi_tx_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_6_hdmi_tx_0_0 || ORIG_REF_NAME==design_6_hdmi_tx_0_0} -quiet] -quiet

# XDC: c:/Users/alexj/Downloads/Soc_FinalProject-Task2/project_2.xpr/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_myip_pong2_0_0/src/design_6_clk_wiz_0_0/design_6_clk_wiz_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_6_clk_wiz_0_0 || ORIG_REF_NAME==design_6_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/alexj/Downloads/Soc_FinalProject-Task2/project_2.xpr/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_myip_pong2_0_0/src/design_6_clk_wiz_0_0/design_6_clk_wiz_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_6_clk_wiz_0_0 || ORIG_REF_NAME==design_6_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/alexj/Downloads/Soc_FinalProject-Task2/project_2.xpr/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_myip_pong2_0_0/src/design_6_clk_wiz_0_0/design_6_clk_wiz_0_0_late.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_6_clk_wiz_0_0 || ORIG_REF_NAME==design_6_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/alexj/Downloads/Soc_FinalProject-Task2/project_2.xpr/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_myip_pong2_0_0/src/design_6_clk_wiz_0_0/design_6_clk_wiz_0_0_ooc.xdc

# XDC: c:/Users/alexj/Downloads/Soc_FinalProject-Task2/project_2.xpr/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_myip_pong2_0_0/src/design_6_ooc.xdc
